"""Initial migration

Revision ID: cc2d2d14466a
Revises: 
Create Date: 2023-12-06 10:05:46.989896

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc2d2d14466a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('admin_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=45), nullable=False),
    sa.Column('last_name', sa.String(length=45), nullable=False),
    sa.Column('email', sa.String(length=45), nullable=True),
    sa.Column('phone_number', sa.String(length=45), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('order_time', sa.Time(), nullable=False),
    sa.Column('slot_number', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('payment', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.drop_table('Receptions')
    op.drop_table('Patients')
    op.drop_table('MedicalRecords')
    op.drop_table('Appointments')
    op.drop_table('Doctors')
    op.drop_table('Billings')
    op.drop_table('Admins')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Admins',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('role', mysql.VARCHAR(length=6), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=15), nullable=False),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('Billings',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('patient_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('reception_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('amount', mysql.FLOAT(), nullable=False),
    sa.Column('payment_date', mysql.DATETIME(), nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('Doctors',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('role', mysql.VARCHAR(length=6), nullable=False),
    sa.Column('specialty', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('firstname', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('lastname', mysql.VARCHAR(length=80), nullable=False),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('Appointments',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('patient_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('doctor_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('time', mysql.TIME(), nullable=False),
    sa.Column('status', mysql.ENUM('pending', 'scheduled', 'completed'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('reason', mysql.TEXT(), nullable=False),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('MedicalRecords',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('patient_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('doctor_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=12), nullable=True),
    sa.Column('diagnosis', mysql.TEXT(), nullable=False),
    sa.Column('prescription', mysql.TEXT(), nullable=False),
    sa.Column('testresult', mysql.TEXT(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('Patients',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('firstname', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('lastname', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('dateofbirth', sa.DATE(), nullable=False),
    sa.Column('gender', mysql.VARCHAR(length=1), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('subcity', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('wereda', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('house_number', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('medicalhistory', mysql.TEXT(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('Receptions',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('firstname', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('lastname', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('role', mysql.VARCHAR(length=9), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('orders')
    op.drop_table('admins')
    # ### end Alembic commands ###
